### ISSUE TITLE
堪え性のない砲撃手のイベントにて

### ISSUE THREAD

**Issue by s172262** [HyperUrchin/ssjptr#1]
いつもお世話になっております

「堪え性のない砲撃手」との食事イベントにて、
>「鉄と嘆きの商会は確か、何か実験をしていた筈です」
>「私をデュモー島に連れて行ってくれませんか?」

という和訳文があるのですが、こちらについて表記の揺れとなっており、

「鉄と嘆きの商会」はMapなどでは「アイアン&ミザリー社」、
「デュモー島」は"Demeaux Island" なので、Mapなどでは「デミオー・アイランド」となっています。

ご確認の程、よろしくお願いいたします。

また、そのデミオー・アイランドにある "Funging station" について、「ボルチーニ茸を栽培して建材にしている」との説明があるので、
「キノコ栽培所」と意訳してしまうのはいかがでしょうか?

**Comment by kimi64** [comment]
ご報告ありがとうございます。コメントに気づかず返信が遅れてしまってすみません。

今回指摘いただいた表記揺れについてはどちらも用語統一以前の訳が残っている箇所になります。現在日本語化ファイル本体の更新は休止中ですが、Github上のテキストではこれらの箇所もCampaignerなどの一部を除き一通り修正されていますので、次回日本語化ファイル更新時に修正が反映される予定です。

用語の変更についてもそのような状況ですのですぐに変更、修正するというのは難しいのですが、更新が再開されることがあればその時に再考させていただきます。

他にもお気づきの点があればまたぜひご報告ください。
