### ISSUE TITLE
Port Carnelian のイベントでの表記の揺れ

### ISSUE THREAD

**Issue by s172262** [HyperUrchin/ssjptr#2]
いつもお世話になっております。

"Khan" について、ほぼほぼ全編に渡って「カーン」に訳されておられるのですが、
Port Carnelian のイベント"Call at a room above a bookshop"にて、
"Oh, the Khan is very fond of sapphires. Blue is his favourite colour."の訳の部分で
「ハーン」となっております。

ご確認ください

**Comment by kimi64** [comment]
一つ前のイシューをご確認ください。
